package hzuo.euler._017

object Languages {

  val cn = List(
    "1" -> "yi",
    "2" -> "er",
    "3" -> "san",
    "4" -> "si",
    "5" -> "wu",
    "6" -> "liu",
    "7" -> "qi",
    "8" -> "ba",
    "9" -> "jiu",
    "(#)(#)" -> "shi",
    "1(#)" -> "shi",
    "(#)(##)" -> "bai",
    "(#)(###)" -> "qian",
    "(#+)(####)" -> "wan",
    "(#+)(########)" -> "yi")

  val en = List(
    "1" -> "one",
    "2" -> "two",
    "3" -> "three",
    "4" -> "four",
    "5" -> "five",
    "6" -> "six",
    "7" -> "seven",
    "8" -> "eight",
    "9" -> "nine",
    "10" -> "ten",
    "11" -> "eleven",
    "12" -> "twelve",
    "13" -> "thirteen",
    "14" -> "fourteen",
    "15" -> "fifteen",
    "16" -> "sixteen",
    "17" -> "seventeen",
    "18" -> "eighteen",
    "19" -> "nineteen",
    "2(#)" -> "twenty",
    "3(#)" -> "thirty",
    "4(#)" -> "forty",
    "5(#)" -> "fifty",
    "6(#)" -> "sixty",
    "7(#)" -> "seventy",
    "8(#)" -> "eighty",
    "9(#)" -> "ninety",
    "(#)(##)" -> "hundred",
    "(#+)(###)" -> "thousand",
    "(#+)(######)" -> "million",
    "(#+)(#########)" -> "billion",
    "(#+)(############)" -> "trillion")

  val fr = List(
    "1" -> "un",
    "2" -> "deux",
    "3" -> "trois",
    "4" -> "quatre",
    "5" -> "cinq",
    "6" -> "six",
    "7" -> "sept",
    "8" -> "huit",
    "9" -> "neuf",
    "1(#)" -> "dix-",
    "10" -> "dix",
    "11" -> "onze",
    "12" -> "douze",
    "13" -> "treize",
    "14" -> "quatorze",
    "15" -> "quinze",
    "16" -> "seize",
    "2(#)" -> "vingt",
    "21" -> "vingt et un",
    "3(#)" -> "trente",
    "31" -> "trente et un",
    "4(#)" -> "quarante",
    "41" -> "quarante et un",
    "5(#)" -> "cinquante",
    "51" -> "cinquante et un",
    "6(#)" -> "soixante",
    "61" -> "soixante et un",
    "7(#)" -> "soixante-dix-",
    "70" -> "soixante dix",
    "71" -> "soixante et onze",
    "72" -> "soixante-douze",
    "73" -> "soixante-treize",
    "74" -> "soixante-quatorze",
    "75" -> "soixante-quinze",
    "76" -> "soixante-seize",
    "8(#)" -> "quatre-vingts-",
    "80" -> "quatre-vingts",
    "9(#)" -> "quatre-vingt-dix-",
    "90" -> "quatre-vingt-dix",
    "91" -> "quatre-vingt-onze",
    "92" -> "quatre-vingt-douze",
    "93" -> "quatre-vingt-treize",
    "94" -> "quatre-vingt-quatorze",
    "95" -> "quatre-vingt-quinze",
    "96" -> "quatre-vingt-seize",
    "(#)(##)" -> "cent",
    "(#)(00)" -> "cents",
    "1(##)" -> "cent",
    "(#+)(###)" -> "mille",
    "1(###)" -> "mille",
    "(#+)(######)" -> "millions",
    "(1)(######)" -> "million",
    "(#+)(#########)" -> "milliards",
    "(1)(#########)" -> "milliard",
    "(#+)(############)" -> "trillion")

}